import { MenuBar } from '@/components/MenuBar/MenuBar'
import { Social_Bubble } from '@/components/MenuBar/Social_Bubble'
import { SideBar } from '@/components/SideBar/SideBar'
import Head from 'next/head'
import styled from 'styled-components'

const MainContents = styled.div`
    position: relative;
    height: calc(100vh - 95px);
    padding-top: 95px;
    margin: 0 auto;
    margin-left: 120px;
`

const Wallpaper = styled.div`
    position: fixed;
    width: 100%;
    height: 100vh;
    background-position: center;
    background-size: cover;
    z-index: -100;
`

const TitleBox = styled.div`
    display: inline-flex;
    flex-direction: column;
    position: absolute;
    left: 20px;
    bottom: 40px;
    gap: 30px;
`

const TextBox = styled.div`
    display: flex;
    flex-direction: column;
`

export default function Archives_User_Top() {
    const image = "/DummyAssets/52e59d9a59265fac16a891cd33b98272.png";

    return (
        <>
        <Head>
            <title>Group Name - トップ</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <Wallpaper style={{backgroundImage: `linear-gradient(180deg, rgba(0, 0, 0, 0.00) 37.5%, rgba(0, 0, 0, 0.70) 100%), url(${image})`}}/>
            <SideBar />
            <MenuBar subtitle={"WiP"} title={"IdolVerse"} />
            <MainContents>
                <TitleBox>
                    <TextBox>
                        <div class="t-FullScreen-Title tC-fff">Group<br/>Naaaaame</div>
                        <div class="t-BlockTitle-Bolder tC-Dark-Text">300人のフォロワー</div>
                    </TextBox>
                    <Social_Bubble/>
                </TitleBox>
            </MainContents>
        </main>
        </>
    )
}
