import { MenuBar } from '@/components/MenuBar/MenuBar'
import { SideBar } from '@/components/SideBar/SideBar'
import Head from 'next/head'
import styled from 'styled-components'
import { BannerSlide } from '@/components/Assets/BannerSlide'
import { ListWrapper } from '@/components/Assets/List/ListWrapper'
import { Contexts_Def } from '@/components/Assets/List/Contexts/Contexts_Def'
import { SVG_book, SVG_calendar, SVG_guide_board } from '@/components/IconPack'

const MainContents = styled.div`
    max-width: 1020px;
    position: relative;
    top: 95px;
    margin: 0 auto;

    @media (max-width: 1260px) {
        margin-left: 120px;
    }
`

const Top = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 30px;
`

const Title = styled.div`
    margin-right: auto;
`

const Wallpaper = styled.div`
    position: fixed;
    width: 100%;
    height: 100%;
    /* background: var(--BG, linear-gradient(180deg, #80D9FF 0%, rgba(128, 217, 255, 0.00) 32.81%), radial-gradient(100% 100% at 50% 0%, #80D9FF 0%, #DAF6FF 69.27%, #FFF2F8 100%)); */
    z-index: -100;
`

export default function Archives_User_Top() {
    const image = "/DummyAssets/52e59d9a59265fac16a891cd33b98272.png";

    return (
        <>
        <Head>
            <title>Group Name - トップ - IdolVerse アーカイブ</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <Wallpaper style={{background: `no-repeat url(${image})`}}/>
            <SideBar />
            <MenuBar subtitle={"WiP"} title={"IdolVerse"} />
            <MainContents>
            <Top>
                <Title>
                <div className='t-Max-Bolder'>IdolVerse</div>
                <div className='t-SubMax-Regular tC-TextSub'>Working in Progress...</div>
                </Title>
                <BannerSlide title={"最近の出来事"} />
                <ListWrapper
                title={"クイックアクセス"}
                column={"3"}
                Contexts={
                    <>
                    <Contexts_Def
                        svg={<SVG_calendar size={30} />}
                        title={"予定を見る"}
                        subTitle={"イベントカレンダー"}
                    />
                    <Contexts_Def
                        svg={<SVG_guide_board size={30} />}
                        title={"交流する"}
                        subTitle={"コミュニティ"}
                    />
                    <Contexts_Def
                        link={"/archives/mainlist"}
                        svg={<SVG_book size={30} />}
                        title={"過去を振りかえる"}
                        subTitle={"アーカイブ"}
                    />
                    </>
                }
                />
            </Top>
            </MainContents>
        </main>
        </>
    )
}
