import { Buttons2 } from "@/components/Assets/Buttons2";
import { Contexts_User } from "@/components/Assets/List/Contexts/Contexts_User";
import { ListWrapper } from "@/components/Assets/List/ListWrapper";
import { MenuBar } from "@/components/MenuBar/MenuBar";
import { SideBar } from "@/components/SideBar/SideBar";
import Head from "next/head";
import styled from "styled-components";

const MainContents = styled.div`
  max-width: 1020px;
  position: relative;
  top: 95px;
  margin: 0 auto;

  @media (max-width: 1260px) {
    margin-left: 120px;
  }
`;

export default function MainList() {
  return (
    <>
      <Head>
        <title>アーカイブ - IdolVerse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="wallpaper"></div>
        <SideBar />
        <MenuBar title={"アーカイブ"} />
        <MainContents>
          <Buttons2 title={"リスト"} />
          <ListWrapper
            title={"リスト"}
            column={"4"}
            Contexts={
              <Contexts_User
                title={"Group Name"}
                theme={"Theme"}
                followersCount={"Num of Followers"}
              />
            }
          />
        </MainContents>
      </main>
    </>
  );
}
